name: Tests

on:
  push:
    branches: [master]
    paths-ignore: ['*.md']
  pull_request:
    type: [opened, reopened, edited]
    paths-ignore: ['*.md']

jobs:

  spec:
    name: Spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5.x'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run spec tests
        run: bundle exec rake spec
